[build-system]
# Defined by PEP 518
requires = [
  "setuptools>=45",
  "wheel",
]
# Defined by PEP 517
build-backend = "setuptools.build_meta"


[tool.black]
line-length = 79
target-version = ['py37', 'py38']
include = '\.pyi?$'
extend-exclude = '''
(
  /(
    | sphinxext
    | tools
    | benchmarks\/\.asv.*
  )/
  | _ff_cross_references.py
  | um_cf_map.py
)
'''

[tool.isort]
force_sort_within_sections = "True"
known_first_party = "iris"
line_length = 79
profile = "black"
extend_skip = [
  "_build",
  "generated",
  "sphinxext",
  "tools",
]
skip_gitignore = "True"
verbose = "False"
