# A workflow to do PR test runs

name: pr-tests

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: create conda test env
        run: $CONDA/bin/conda create -n testenv python=3.8

      - name: install dependencies
        run: $CONDA/bin/conda install -n testenv pytest netCDF4

      - name: run tests
        run: |
          source $CONDA/bin/activate testenv
          pytest lib/ugrid_checks/tests
