# A workflow to do PR test runs

name: pr-tests

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install conda
        run: pip install conda

      - name: create test env
        run: |
          conda create -y -n testenv python=3.8

      - name: debug pwd1
        run: pwd

      - name: debug conda loc
        run: echo $(which conda)

      - name: activate (will fail?)
        run: conda activate testenv

      - name: install deps
        run: conda install pytest numpy netCDF4

      - name: debug pwd
        run: pwd

      - name: run tests
        run:
          pytest lib/ugrid_checks/tests
