# A workflow to do PR test runs

name: pr-tests

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install netCDF4
        run: pip install netCDF4

      - name: debug nc install
        run: |
          which python
          python -c "import netCDF4 as nc; print(nc)"
          ls /home/runner/.local/bin/nc*

      - name: debug pwd1
        run: pwd

      - name: install other deps
        run: pip install pytest numpy

      - name: debug pwd
        run: pwd

      - name: run tests
        run:
          pytest lib/ugrid_checks/tests
